/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlykhachsan.GUI;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import quanlykhachsan.BUS.thuephongBUS;
import quanlykhachsan.DAO.datphongModify;
import quanlykhachsan.DTO.datphongDTO;
import quanlykhachsan.DTO.thuephongDTO;
import static quanlykhachsan.GUI.LoginGUI.user;
/**
 *
 * @author Duy Minh
 */
public final class thuephongGUI extends javax.swing.JFrame {

    /**
     * Creates new form thuephongGUI
     *
     * @throws java.sql.SQLException
     */
    LoginGUI lg = new LoginGUI();
    public thuephongGUI() throws SQLException, ParseException {
       
        initComponents();
        this.setLocationRelativeTo(null);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog3 = new datechooser.beans.DateChooserDialog();
        Bookroom1 = new javax.swing.JPanel();
        gender1 = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        cmnd1 = new javax.swing.JTextField();
        phonenumber1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        typeofcus1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        fullname1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        birthday1 = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Bookroom1.setBackground(new java.awt.Color(255, 255, 255));
        Bookroom1.setBorder(new javax.swing.border.MatteBorder(null));

        gender1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gender1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykhachsan/HinhAnh/close_window_64px.png"))); // NOI18N
        jLabel31.setText("Close");
        jLabel31.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel31MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel31MouseExited(evt);
            }
        });

        cmnd1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmnd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmnd1ActionPerformed(evt);
            }
        });

        phonenumber1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setText("Customer type:");

        typeofcus1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        typeofcus1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Local", "Foreign" }));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Fullname:");

        fullname1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setText("Birthday:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("CMND:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Address: ");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("Phone number:");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setText("Gender:");

        address1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(address1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Information's customer ");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        birthday1.setCalendarBackground(new java.awt.Color(255, 255, 255));
        birthday1.setCalendarPreferredSize(new java.awt.Dimension(400, 230));
        birthday1.setWeekStyle(datechooser.view.WeekDaysStyle.FULL);
        birthday1.setFieldFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 18));
        birthday1.setLocale(new java.util.Locale("vi", "", ""));

        javax.swing.GroupLayout Bookroom1Layout = new javax.swing.GroupLayout(Bookroom1);
        Bookroom1.setLayout(Bookroom1Layout);
        Bookroom1Layout.setHorizontalGroup(
            Bookroom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Bookroom1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(Bookroom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel24)
                    .addComponent(jLabel27)
                    .addComponent(jLabel25)
                    .addComponent(jLabel10)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addGap(70, 70, 70)
                .addGroup(Bookroom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(birthday1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Bookroom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(typeofcus1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmnd1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(phonenumber1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fullname1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(Bookroom1Layout.createSequentialGroup()
                .addGroup(Bookroom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Bookroom1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Bookroom1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Bookroom1Layout.setVerticalGroup(
            Bookroom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Bookroom1Layout.createSequentialGroup()
                .addGroup(Bookroom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Bookroom1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addGroup(Bookroom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fullname1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGroup(Bookroom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Bookroom1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(Bookroom1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addGroup(Bookroom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(gender1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addComponent(birthday1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Bookroom1Layout.createSequentialGroup()
                        .addContainerGap(296, Short.MAX_VALUE)
                        .addComponent(jLabel29)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(Bookroom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phonenumber1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(40, 40, 40)
                .addGroup(Bookroom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(cmnd1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(Bookroom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27)
                    .addComponent(typeofcus1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(Bookroom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jLabel31)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Bookroom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Bookroom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmnd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmnd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmnd1ActionPerformed

    private void jLabel31MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseExited
        // TODO add your handling code here:
        jLabel31.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel31MouseExited

    private void jLabel31MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseEntered
        // TODO add your handling code here:
        jLabel31.setBackground(Color.LIGHT_GRAY);
        jLabel31.setOpaque(true);
    }//GEN-LAST:event_jLabel31MouseEntered

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:`
        this.dispose();
    }//GEN-LAST:event_jLabel31MouseClicked
         public void load_cus_booked(String madp) throws SQLException, ParseException {
        datphongModify dBus = new datphongModify();
        datphongDTO dp;
        dp = dBus.showCusroom(madp);
//        datphongDTO dp1 = dBus.showngaydadatphong(maroom2.getText());
        fullname1.setText(dp.getHtkh());
        fullname1.setEnabled(false);
        gender1.setSelectedItem(dp.getNgaysinh());
             System.err.println(dp.getGioitinh());
        gender1.setEnabled(false);
        String d = dp.getGioitinh();
             System.err.println(d);
        String substring = d.substring(0, 10);
        System.err.println(substring);
        String ngay = substring.substring(8, 10);
        System.err.println(ngay);
        String thang = substring.substring(5, 7);
        System.err.println(thang);
        String nam = substring.substring(0, 4);
        System.err.println(nam);
        String ngaythangnam = ngay + '-' + thang + '-' + nam;
        System.err.println(ngaythangnam);
        Calendar a = Calendar.getInstance();
        a.setTime(new SimpleDateFormat("dd-MM-yyyy").parse(ngaythangnam));
        birthday1.setSelectedDate(a);
        birthday1.setEnabled(Boolean.FALSE);
        String user1 = user;                              
        phonenumber1.setText(dp.getSodt());
        phonenumber1.setEnabled(false);
        cmnd1.setText(dp.getCmnd());
        cmnd1.setEnabled(false);
        typeofcus1.setSelectedItem(dp.getLoaikhach());
        typeofcus1.setEnabled(false);
        address1.setText(dp.getDiachi());
        address1.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FlatLightLaf.install();
                try {
                    try {
                        new thuephongGUI().setVisible(true);
                    } catch (ParseException ex) {
                        Logger.getLogger(thuephongGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(thuephongGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel Bookroom1;
    private javax.swing.JEditorPane address1;
    private datechooser.beans.DateChooserCombo birthday1;
    private javax.swing.JTextField cmnd1;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private datechooser.beans.DateChooserDialog dateChooserDialog3;
    private javax.swing.JTextField fullname1;
    private javax.swing.JComboBox<String> gender1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField phonenumber1;
    private javax.swing.JComboBox<String> typeofcus1;
    // End of variables declaration//GEN-END:variables
}
