/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlykhachsan.GUI;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import quanlykhachsan.BUS.datphongBUS;
import quanlykhachsan.BUS.dichvuBUS;
import quanlykhachsan.BUS.hoadonBUS;
import quanlykhachsan.BUS.phieudatdvBUS;
import quanlykhachsan.BUS.phongBUS;
import quanlykhachsan.DAO.ConnectDataBase;
import quanlykhachsan.DAO.iReportDAO;
import quanlykhachsan.DTO.phieudatdvDTO;
import static quanlykhachsan.GUI.Bookroom.maroom1;
import static quanlykhachsan.GUI.dichvuGUI.tendv1;
import static quanlykhachsan.GUI.dichvuGUI.gia1;

/**
 *
 * @author Duy Minh
 */
public final class tieptanGUI extends javax.swing.JFrame {

    CardLayout cl;
    Bookroom br;
    thuephongGUI tp = new thuephongGUI();
    dichvuGUI dv ;
    static String checkinString, checkoutString;

    /**
     * Creates new form nhanvien
     *
     * @throws java.sql.SQLException
     * @throws java.text.ParseException
     */
    public tieptanGUI() throws SQLException, ParseException {

        initComponents();
        this.setLocationRelativeTo(null);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        cl = (CardLayout) (jPanel3.getLayout());
        cl.show(jPanel3, "card2");
        //   load_table_allRoom();
        //  load_table_emproom();
        load_table_bookroom();
    }

//    public void load_table_emproom() throws SQLException {
//        phongBUS pBUS = new phongBUS();
//        pBUS.showphongtrong((DefaultTableModel) tblphongtrong.getModel());
//
//    }
//    public void load_table_emproom_bookroom() throws SQLException {
//        phongBUS pBUS = new phongBUS();
//        pBUS.showphongtrongvadadat((DefaultTableModel) tblphongtrongvadadat.getModel());
//    }
    public void load_table_allRoom() throws SQLException {
        phongBUS pBUS = new phongBUS();
        pBUS.showphong((DefaultTableModel) tblphongcosan.getModel());
    }

    public void load_table_bookroom() throws SQLException {
        datphongBUS dpBUS = new datphongBUS();
        dpBUS.showphong((DefaultTableModel) tblbookroom.getModel());
    }

//    public void load_phieu_thue_phong() throws SQLException {
//        thuephongBUS tpBUS = new thuephongBUS();
//        tpBUS.showphong((DefaultTableModel) tblbookroom1.getModel());
//    }
//    public void load_phieu_thue_phong_2() throws SQLException {
//        thuephongBUS tpBUS = new thuephongBUS();
//        tpBUS.showphong((DefaultTableModel) tbltraphong.getModel());
//    }
    public void load_table_dichvu() throws SQLException {
        dichvuBUS dvBUS = new dichvuBUS();
        dvBUS.showdichvu((DefaultTableModel) tbldichvu.getModel());
    }

    public void load_sddv() throws SQLException {
        phieudatdvBUS sddv = new phieudatdvBUS();
        sddv.showsddv((DefaultTableModel) tblsddv.getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        datphong1 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        tblphongcosan = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        tblbookroom = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        timkiemroom = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        roomtype2 = new javax.swing.JComboBox<>();
        checkout = new com.toedter.calendar.JDateChooser();
        checkin = new com.toedter.calendar.JDateChooser();
        dichvubill = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tbldichvu = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        tblsddv = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        hoadon = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblhddv = new javax.swing.JTable();
        jScrollPane18 = new javax.swing.JScrollPane();
        tblhoadonphong = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        maphong5 = new javax.swing.JTextField();
        inhoadon = new javax.swing.JLabel();
        timkiemphong3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 0, 102));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykhachsan/HinhAnh/back_to_40px.png"))); // NOI18N
        jLabel6.setText("Back");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Receptionist");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykhachsan/HinhAnh/key_48px.png"))); // NOI18N
        jLabel2.setText("             Book room");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 0, 51)));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykhachsan/HinhAnh/invoice_64px.png"))); // NOI18N
        jLabel35.setText("               Invoiced");
        jLabel35.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 0, 51)));
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel35MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel35MouseExited(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykhachsan/HinhAnh/service_bell_40px.png"))); // NOI18N
        jLabel37.setText("        Service billing");
        jLabel37.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 0, 51)));
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel37MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel37MouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykhachsan/HinhAnh/exit_100px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 15, Short.MAX_VALUE))
            .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(91, 91, 91))))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(24, 24, 24))
        );

        jPanel3.setLayout(new java.awt.CardLayout());

        datphong1.setBackground(new java.awt.Color(255, 255, 255));
        datphong1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                datphong1MouseMoved(evt);
            }
        });
        datphong1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                datphong1FocusGained(evt);
            }
        });
        datphong1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                datphong1MouseEntered(evt);
            }
        });
        datphong1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                datphong1ComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                datphong1ComponentShown(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Rage Italic", 2, 36)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 153, 0));
        jLabel36.setText("Romance hotel ");

        jPanel15.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );

        tblphongcosan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblphongcosan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Code room", "Room type", "Unit Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblphongcosan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tblphongcosanMouseMoved(evt);
            }
        });
        tblphongcosan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblphongcosanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblphongcosanMouseEntered(evt);
            }
        });
        jScrollPane12.setViewportView(tblphongcosan);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Available Room list");

        tblbookroom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblbookroom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Code book room ", "Code room", "Check-in Date", "Check-out Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblbookroom.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tblbookroomMouseMoved(evt);
            }
        });
        tblbookroom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbookroomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblbookroomMouseEntered(evt);
            }
        });
        jScrollPane13.setViewportView(tblbookroom);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Reservation Details");

        timkiemroom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        timkiemroom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timkiemroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykhachsan/HinhAnh/search_48px (2).png"))); // NOI18N
        timkiemroom.setText("Search room");
        timkiemroom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        timkiemroom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timkiemroomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                timkiemroomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                timkiemroomMouseExited(evt);
            }
        });

        jLabel55.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel55.setText("Check-in date:");

        jLabel56.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel56.setText("Room type");

        jLabel57.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel57.setText("Check-out date:");

        roomtype2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        roomtype2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vip", "Afordable", "Luxury" }));

        checkout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        checkin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout datphong1Layout = new javax.swing.GroupLayout(datphong1);
        datphong1.setLayout(datphong1Layout);
        datphong1Layout.setHorizontalGroup(
            datphong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(datphong1Layout.createSequentialGroup()
                .addComponent(jLabel36)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datphong1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(datphong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(datphong1Layout.createSequentialGroup()
                        .addComponent(jLabel56)
                        .addGap(91, 91, 91)
                        .addComponent(roomtype2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(timkiemroom, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(datphong1Layout.createSequentialGroup()
                        .addGroup(datphong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel57)
                            .addComponent(jLabel55))
                        .addGap(55, 55, 55)
                        .addGroup(datphong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkin, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(checkout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addGroup(datphong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        datphong1Layout.setVerticalGroup(
            datphong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datphong1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(datphong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(datphong1Layout.createSequentialGroup()
                        .addGroup(datphong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(datphong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(datphong1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(datphong1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(datphong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(datphong1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(datphong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(timkiemroom)
                                    .addComponent(roomtype2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel56, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(datphong1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel3.add(datphong1, "card4");

        dichvubill.setBackground(new java.awt.Color(255, 255, 255));
        dichvubill.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                dichvubillMouseMoved(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Rage Italic", 2, 36)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 153, 0));
        jLabel38.setText("Romance hotel ");

        jPanel17.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );

        tbldichvu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbldichvu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Service code ", "Service name", "Unit of calculation", "Unit Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbldichvu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tbldichvuMouseMoved(evt);
            }
        });
        tbldichvu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldichvuMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(tbldichvu);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Service voucher");

        tblsddv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblsddv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Service voiucher  code ", "Room code", "Service name ", "Date", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblsddv.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tblsddvMouseMoved(evt);
            }
        });
        tblsddv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsddvMouseClicked(evt);
            }
        });
        jScrollPane16.setViewportView(tblsddv);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Service list");

        javax.swing.GroupLayout dichvubillLayout = new javax.swing.GroupLayout(dichvubill);
        dichvubill.setLayout(dichvubillLayout);
        dichvubillLayout.setHorizontalGroup(
            dichvubillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dichvubillLayout.createSequentialGroup()
                .addComponent(jLabel38)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(dichvubillLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(dichvubillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(dichvubillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        dichvubillLayout.setVerticalGroup(
            dichvubillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dichvubillLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addGroup(dichvubillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dichvubillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addComponent(jScrollPane10))
                .addGap(20, 20, 20))
        );

        jPanel3.add(dichvubill, "card5");

        hoadon.setBackground(new java.awt.Color(255, 255, 255));
        hoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hoadonMouseClicked(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Rage Italic", 2, 36)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 153, 0));
        jLabel39.setText("Romance hotel ");

        jPanel19.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );

        tblhddv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblhddv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Code room", "Service name", " Mount", "Unit Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblhddv.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tblhddvMouseMoved(evt);
            }
        });
        jScrollPane11.setViewportView(tblhddv);

        tblhoadonphong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblhoadonphong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Code room", "Type room", "Unit of calculation", "Date stay", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblhoadonphong.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tblhoadonphongMouseMoved(evt);
            }
        });
        jScrollPane18.setViewportView(tblhoadonphong);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Service Invoice Information");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Invoices Communication Room");

        maphong5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maphong5.setToolTipText("Customer's fullname");
        maphong5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        maphong5.setName("Customer's fullname"); // NOI18N
        maphong5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                maphong5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                maphong5FocusLost(evt);
            }
        });
        maphong5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maphong5ActionPerformed(evt);
            }
        });
        maphong5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                maphong5KeyPressed(evt);
            }
        });

        inhoadon.setBackground(new java.awt.Color(255, 255, 255));
        inhoadon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        inhoadon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inhoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykhachsan/HinhAnh/print_80px.png"))); // NOI18N
        inhoadon.setText("Print bill");
        inhoadon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inhoadonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inhoadonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inhoadonMouseExited(evt);
            }
        });

        timkiemphong3.setBackground(new java.awt.Color(255, 255, 255));
        timkiemphong3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        timkiemphong3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timkiemphong3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykhachsan/HinhAnh/search_48px (2).png"))); // NOI18N
        timkiemphong3.setText("Search room");
        timkiemphong3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        timkiemphong3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timkiemphong3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                timkiemphong3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                timkiemphong3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout hoadonLayout = new javax.swing.GroupLayout(hoadon);
        hoadon.setLayout(hoadonLayout);
        hoadonLayout.setHorizontalGroup(
            hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(hoadonLayout.createSequentialGroup()
                .addComponent(jLabel39)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(hoadonLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hoadonLayout.createSequentialGroup()
                        .addComponent(timkiemphong3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(maphong5, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(inhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        hoadonLayout.setVerticalGroup(
            hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hoadonLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hoadonLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(inhoadon)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hoadonLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timkiemphong3)
                            .addComponent(maphong5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hoadonLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane11))
                    .addGroup(hoadonLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
        );

        jPanel3.add(hoadon, "card6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        LoginGUI lg = new LoginGUI();
        lg.setVisible(true);
        this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        jLabel6.setBackground(Color.LIGHT_GRAY);
        jLabel6.setOpaque(true);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jLabel6.setBackground(new Color(98, 9, 107));    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        cl.show(jPanel3, "card4");                 // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setBackground(Color.LIGHT_GRAY);
        jLabel2.setOpaque(true);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setBackground(new Color(76, 63, 140));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
        // TODO add your handling code here:

        cl.show(jPanel3, "card6");
//        try {
//            load_tra_phong();
//        } catch (SQLException ex) {
//            Logger.getLogger(tieptanGUI.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel35MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseEntered
        // TODO add your handling code here:
        jLabel35.setBackground(Color.LIGHT_GRAY);
        jLabel35.setOpaque(true);
    }//GEN-LAST:event_jLabel35MouseEntered

    private void jLabel35MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseExited
        // TODO add your handling code here:
        jLabel35.setBackground(new Color(70, 77, 148));
    }//GEN-LAST:event_jLabel35MouseExited

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
        // TODO add your handling code here:
        cl.show(jPanel3, "card5");
        try {
            load_table_dichvu();
            load_sddv();
        } catch (SQLException ex) {
            Logger.getLogger(tieptanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel37MouseClicked

    private void jLabel37MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseEntered
        // TODO add your handling code here:
        jLabel37.setBackground(Color.LIGHT_GRAY);
        jLabel37.setOpaque(true);
    }//GEN-LAST:event_jLabel37MouseEntered

    private void jLabel37MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseExited
        // TODO add your handling code here:
        jLabel37.setBackground(new Color(78, 57, 136));
    }//GEN-LAST:event_jLabel37MouseExited

    private void datphong1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_datphong1ComponentShown
        try {
            // TODO add your handling code here:
            load_table_bookroom();
            //   load_table_emproom();
        } catch (SQLException ex) {
            Logger.getLogger(tieptanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_datphong1ComponentShown

    private void datphong1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_datphong1ComponentHidden
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            load_table_bookroom();
            //  load_table_emproom();
        } catch (SQLException ex) {
            Logger.getLogger(tieptanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_datphong1ComponentHidden

    private void datphong1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datphong1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_datphong1MouseEntered

    private void datphong1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_datphong1FocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_datphong1FocusGained

    private void timkiemroomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timkiemroomMouseExited
        timkiemroom.setBackground(Color.WHITE);
    }//GEN-LAST:event_timkiemroomMouseExited

    private void timkiemroomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timkiemroomMouseEntered
        // TODO add your handling code here:
        timkiemroom.setBackground(Color.LIGHT_GRAY);
        timkiemroom.setOpaque(true);
    }//GEN-LAST:event_timkiemroomMouseEntered

    private void timkiemroomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timkiemroomMouseClicked

        Date checkin1 = this.checkin.getDate();
        Date checkout1 = this.checkout.getDate();
        checkinString = checkin1.getDate() + "-" + (checkin1.getMonth() + 1) + "-" + (checkin1.getYear() + 1900);
        checkoutString = checkout1.getDate() + "-" + (checkout1.getMonth() + 1) + "-" + (checkout1.getYear() + 1900);
        String loaiphongString = roomtype2.getSelectedItem().toString();
        datphongBUS dpBUS;

        try {
            dpBUS = new datphongBUS();
            dpBUS.showkhachdadatphong(loaiphongString, checkinString, checkoutString, (DefaultTableModel) tblphongcosan.getModel());
            // try {
            //    load_table_emproom();
            // } catch (SQLException ex) {
            //  Logger.getLogger(tieptanGUI.class.getName()).log(Level.SEVERE, null, ex);
            // }
        } catch (SQLException ex) {
            Logger.getLogger(tieptanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_timkiemroomMouseClicked

    private void tblbookroomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbookroomMouseClicked
        // TODO add your handling code here:

        if (evt.getButton() == 3) {
            JPopupMenu a = new JPopupMenu();
            JMenuItem b = new JMenuItem("  Delete booking room  ");
            b.setFont(new Font("Segoe UI", Font.PLAIN, 18));
            JMenuItem d = new JMenuItem("  Find customer  ");
            d.setFont(new Font("Segoe UI", Font.PLAIN, 18));
            d.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    try {
                        String madp1 = null;
                        int row = tblbookroom.rowAtPoint(evt.getPoint());
                        int col = tblbookroom.columnAtPoint(evt.getPoint());
                        int numcols = tblbookroom.getColumnCount();
                        for (int i = 0; i < numcols; i++) {
                            String str = (String) tblbookroom.getValueAt(row, i);
                            if (i == 0) {
                                madp1 = (String) tblbookroom.getValueAt(row, i);
                            }
                        }

                        tp.load_cus_booked(madp1);
                        tp.setVisible(true);
                    } catch (SQLException | ParseException ex) {
                        Logger.getLogger(tieptanGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });

            b.addActionListener((ActionEvent e) -> {
                int c = JOptionPane.showConfirmDialog(null, "Do you want to delete the data", "Confirm", JOptionPane.YES_NO_OPTION);
                if (c == 0) {

                    try {
                        String madp = null;
                        String maphong = null;
                        int row = tblbookroom.rowAtPoint(evt.getPoint());
                        int col = tblbookroom.columnAtPoint(evt.getPoint());
                        int numcols = tblbookroom.getColumnCount();
                        for (int i = 0; i < numcols; i++) {
                            String str = (String) tblbookroom.getValueAt(row, i);
                            if (i == 0) {
                                madp = (String) tblbookroom.getValueAt(row, i);
                            }
                            if (i == 1) {
                                maphong = (String) tblbookroom.getValueAt(row, i);
                            }

                        }

                        datphongBUS dp = new datphongBUS();
                        dp.xoadatphong(madp);
                        load_table_bookroom();
                        //   load_table_emproom();
                    } catch (SQLException ex) {
                        Logger.getLogger(tieptanGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });

            a.add(b);
            a.add(d);
            a.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tblbookroomMouseClicked

    private void tblbookroomMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbookroomMouseMoved
        // TODO add your handling code here:
        int row = tblbookroom.rowAtPoint(evt.getPoint());
        tblbookroom.setRowSelectionInterval(row, row);
    }//GEN-LAST:event_tblbookroomMouseMoved

    private void tblphongcosanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblphongcosanMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblphongcosanMouseEntered

    private void tblphongcosanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblphongcosanMouseClicked
        try {
            // TODO add your handling code here:
            br =new Bookroom();
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(tieptanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (evt.getButton() == 3) {
            JPopupMenu a = new JPopupMenu();
            JMenuItem b = new JMenuItem("    Book room    ");
            b.setFont(new Font("Segoe UI", Font.PLAIN, 18));
            b.addActionListener((ActionEvent e) -> {
                
                br.setVisible(true);

            });

            a.add(b);
            a.show(evt.getComponent(), evt.getX(), evt.getY());

        }
        int row = tblphongcosan.rowAtPoint(evt.getPoint());
        int col = tblphongcosan.columnAtPoint(evt.getPoint());
        int numcols = tblphongcosan.getColumnCount();
        // String a="";
        for (int i = 0; i < numcols; i++) {
            String str = (String) tblphongcosan.getValueAt(row, i);
            if (i == 0) {
                maroom1.setText(str);
            }
        }
    }//GEN-LAST:event_tblphongcosanMouseClicked

    private void tblphongcosanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblphongcosanMouseMoved
        // TODO add your handling code here:
        int row = tblphongcosan.rowAtPoint(evt.getPoint());
        tblphongcosan.setRowSelectionInterval(row, row);
    }//GEN-LAST:event_tblphongcosanMouseMoved

    private void tblbookroomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbookroomMouseEntered

    }//GEN-LAST:event_tblbookroomMouseEntered

    private void hoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoadonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_hoadonMouseClicked

    private void maphong5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_maphong5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_maphong5FocusGained

    private void maphong5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_maphong5FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_maphong5FocusLost

    private void maphong5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maphong5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maphong5ActionPerformed

    private void maphong5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maphong5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_maphong5KeyPressed

    private void timkiemphong3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timkiemphong3MouseClicked
        // TODO add your handling code here:
        hoadonBUS hd;
        try {
            hd = new hoadonBUS();
            hd.showhoadonphong(maphong5.getText(), (DefaultTableModel) tblhoadonphong.getModel());
            hd.showhoadondichvu(maphong5.getText(), (DefaultTableModel) tblhddv.getModel());
        } catch (SQLException ex) {
            Logger.getLogger(tieptanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_timkiemphong3MouseClicked

    private void timkiemphong3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timkiemphong3MouseEntered
        // TODO add your handling code here:
        timkiemphong3.setBackground(Color.LIGHT_GRAY);
        timkiemphong3.setOpaque(true);
    }//GEN-LAST:event_timkiemphong3MouseEntered

    private void timkiemphong3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timkiemphong3MouseExited
        // TODO add your handling code here:
        timkiemphong3.setBackground(Color.WHITE);
    }//GEN-LAST:event_timkiemphong3MouseExited

    private void tblhoadonphongMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhoadonphongMouseMoved
        // TODO add your handling code here:
        int row = tblhoadonphong.rowAtPoint(evt.getPoint());
        tblhoadonphong.setRowSelectionInterval(row, row);
    }//GEN-LAST:event_tblhoadonphongMouseMoved

    private void tblhddvMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhddvMouseMoved
        // TODO add your handling code here:s
        int row = tblhddv.rowAtPoint(evt.getPoint());
        tblhddv.setRowSelectionInterval(row, row);
    }//GEN-LAST:event_tblhddvMouseMoved

    private void datphong1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datphong1MouseMoved
        // TODO add your handling code here:
        try {
            //        try {
//            // TODO add your handling code here:
//            load_table_allRoom();
//        } catch (SQLException ex) {
//            Logger.getLogger(tieptanGUI.class.getName()).log(Level.SEVERE, null, ex);
//        }
            load_table_bookroom();
        } catch (SQLException ex) {
            Logger.getLogger(tieptanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_datphong1MouseMoved

    private void inhoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inhoadonMouseClicked
        // TODO add your handling code here:
        hoadonBUS hd;
        iReportDAO ir;
        try {
            ir = new iReportDAO();
            hd = new hoadonBUS();
            hd.themhoadon(maphong5.getText());
            ir.hoadon(maphong5.getText());
        } catch (SQLException | JRException ex) {
            Logger.getLogger(tieptanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_inhoadonMouseClicked

    private void inhoadonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inhoadonMouseEntered
        // TODO add your handling code here:
        inhoadon.setBackground(Color.LIGHT_GRAY);
        inhoadon.setOpaque(true);
    }//GEN-LAST:event_inhoadonMouseEntered

    private void inhoadonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inhoadonMouseExited
        // TODO add your handling code here:
        inhoadon.setBackground(Color.WHITE);

    }//GEN-LAST:event_inhoadonMouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        jLabel7.setBackground(Color.LIGHT_GRAY);
        jLabel7.setOpaque(true);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
        jLabel7.setBackground(new Color(27, 186, 213));
    }//GEN-LAST:event_jLabel7MouseExited

    private void dichvubillMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dichvubillMouseMoved
        try {
            // TODO add your handling code here:
            load_sddv();
        } catch (SQLException ex) {
            Logger.getLogger(tieptanGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_dichvubillMouseMoved

    private void tblsddvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsddvMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == 3) {
            JPopupMenu a = new JPopupMenu();
            JMenuItem b = new JMenuItem("    Delete service voucher  ");
            b.setFont(new Font("Segoe UI", Font.PLAIN, 18));
            b.addActionListener((ActionEvent e) -> {
                String massdv = (String) tblsddv.getValueAt(tblsddv.rowAtPoint(evt.getPoint()), 0);
                phieudatdvDTO sddv = new phieudatdvDTO(massdv);
                phieudatdvBUS sddvBUS;
                try {
                    sddvBUS = new phieudatdvBUS();

                    int c = JOptionPane.showConfirmDialog(null, "Do you want to delete the data", "Confirm", JOptionPane.YES_NO_OPTION);
                    if (c == 0) {

                        if (sddvBUS.xoaphieudv(sddv) == true) {
                            JOptionPane.showMessageDialog(null, "deleted successfully", "Notice", JOptionPane.NO_OPTION);
                        } else {
                            JOptionPane.showMessageDialog(null, "deleted successfully", "Notice", JOptionPane.NO_OPTION);
                        }
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(tieptanGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    load_sddv();
                } catch (SQLException ex) {
                    Logger.getLogger(tieptanGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            });

            a.add(b);
            a.show(evt.getComponent(), evt.getX(), evt.getY());

        }
    }//GEN-LAST:event_tblsddvMouseClicked

    private void tblsddvMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsddvMouseMoved
        // TODO add your handling code here:
        int row = tblsddv.rowAtPoint(evt.getPoint());
        tblsddv.setRowSelectionInterval(row, row);
    }//GEN-LAST:event_tblsddvMouseMoved

    private void tbldichvuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldichvuMouseClicked
        // TODO add your handling code here:
        dv = new dichvuGUI();
        if (evt.getButton() == 3) {
            JPopupMenu a = new JPopupMenu();
            JMenuItem b = new JMenuItem("    Sign up service  ");
            b.setFont(new Font("Segoe UI", Font.PLAIN, 18));
            b.addActionListener((ActionEvent e) -> {
                String madv = (String) tbldichvu.getValueAt(tbldichvu.rowAtPoint(evt.getPoint()), 0);
                String tendv = (String) tbldichvu.getValueAt(tbldichvu.rowAtPoint(evt.getPoint()), 1);
                String gia = (String) tbldichvu.getValueAt(tbldichvu.rowAtPoint(evt.getPoint()), 3);
                tendv1.setText(tendv);
                gia1.setText(gia);
                dv.setVisible(true);
            });

            a.add(b);
            a.show(evt.getComponent(), evt.getX(), evt.getY());

        }
    }//GEN-LAST:event_tbldichvuMouseClicked

    private void tbldichvuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldichvuMouseMoved
        // TODO add your handling code here:int row = tblphongcosan.rowAtPoint(evt.getPoint());
        int row = tbldichvu.rowAtPoint(evt.getPoint());
        tbldichvu.setRowSelectionInterval(row, row);
    }//GEN-LAST:event_tbldichvuMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatLightLaf.install();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                try {
                    new tieptanGUI().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(tieptanGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(tieptanGUI.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser checkin;
    private com.toedter.calendar.JDateChooser checkout;
    public static javax.swing.JPanel datphong1;
    private javax.swing.JPanel dichvubill;
    private javax.swing.JPanel hoadon;
    private javax.swing.JLabel inhoadon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JSeparator jSeparator1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField maphong5;
    private javax.swing.JComboBox<String> roomtype2;
    public static javax.swing.JTable tblbookroom;
    private javax.swing.JTable tbldichvu;
    private javax.swing.JTable tblhddv;
    private javax.swing.JTable tblhoadonphong;
    public static javax.swing.JTable tblphongcosan;
    private javax.swing.JTable tblsddv;
    private javax.swing.JLabel timkiemphong3;
    private javax.swing.JLabel timkiemroom;
    // End of variables declaration//GEN-END:variables
}
